version: '3.1'
services:
  db:
    image: isidroevc/pwadatabase
    command: mysqld --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    network_mode: host
  app: 
    image: isidroevc/pwaapp
    ports:
      - "8080:8080"
    network_mode: host
